version: 0.2

env:
  variables:
    DOTNET_ROOT: /root/.dotnet
  paths:
    - /root/.dotnet

phases:
  install:
    commands:
      - echo "Installing .NET 10 SDK..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 10.0 --quality daily --install-dir /root/.dotnet
      - echo 'export DOTNET_ROOT=/root/.dotnet' | sudo tee /etc/profile.d/dotnet.sh > /dev/null
      - echo 'export PATH=/root/.dotnet:$PATH' | sudo tee -a /etc/profile.d/dotnet.sh > /dev/null
      - source /etc/profile.d/dotnet.sh && ln -sf /root/.dotnet/dotnet /usr/local/bin/dotnet
      - source /etc/profile.d/dotnet.sh && dotnet --info | head -n 20
  pre_build:
    commands:
      - echo "Installing test dependencies..."
      - dotnet restore src/claim-status-api/claim-status-api.csproj
      - echo "Running code analysis..."
      - dotnet build src/claim-status-api/claim-status-api.csproj --configuration Release

  build:
    commands:
      - echo "Running unit tests..."
      - dotnet test src/claim-status-api/claim-status-api.csproj --configuration Release --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage"
      - echo "Running integration tests..."
      - dotnet test src/claim-status-api/claim-status-api.csproj --configuration Release --filter "Category=Integration" || true

  post_build:
    commands:
      - echo "Test execution completed"
      - ls -la src/claim-status-api/

artifacts:
  files:
    - 'src/**/*'
  name: TestArtifact

reports:
  UnitTestReport:
    files:
      - '**/TestResults/**/*.trx'
    file-format: 'JUNITXML'
  CodeCoverageReport:
    files:
      - '**/coverage.cobertura.xml'
    file-format: 'COBERTURAXML'

cache:
  paths:
    - '/root/.dotnet/**/*'
    - '/root/.nuget/**/*'
