version: 0.2

env:
  variables:
    CLUSTER_NAME: materclaims-cluster
    NAMESPACE: materclaims
    SERVICE_DIR: src/claim-status-api

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
  pre_build:
    commands:
      - echo "Configuring kubectl for EKS cluster $CLUSTER_NAME..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - echo "Verifying cluster connection..."
      - kubectl version --client
      - kubectl get nodes
  build:
    commands:
      - echo "Ensuring namespace $NAMESPACE exists..."
      - kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
      - echo "Fetching AWS Account ID and preparing environment variables..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - echo "AWS Account ID:" '$AWS_ACCOUNT_ID'
      - echo "ECR Registry:" '$ECR_REGISTRY'
      - echo "Substituting environment variables in manifests..."
      - envsubst < $SERVICE_DIR/k8s/service-account.yaml > serviceaccount-substituted.yaml
      - envsubst < $SERVICE_DIR/k8s/claim-status-api-deployment.yaml > deployment-substituted.yaml
      - envsubst < $SERVICE_DIR/k8s/claim-status-api-service.yaml > service-substituted.yaml
      - echo "--- Service Account manifest ---"
      - cat serviceaccount-substituted.yaml
      - echo "--- Deployment manifest ---"
      - cat deployment-substituted.yaml
      - echo "--- Service manifest ---"
      - cat service-substituted.yaml
      - echo "Applying Kubernetes manifests to namespace $NAMESPACE..."
      - kubectl apply -f serviceaccount-substituted.yaml
      - kubectl apply -f deployment-substituted.yaml
      - kubectl apply -f service-substituted.yaml
      - echo "Applying HorizontalPodAutoscaler..."
      - kubectl apply -f $SERVICE_DIR/k8s/claim-status-api-hpa.yaml
      - echo "Applying VerticalPodAutoscaler..."
      - kubectl apply -f $SERVICE_DIR/k8s/claim-status-api-vpa.yaml
  post_build:
    commands:
      - echo "Deployment complete. Checking pod status..."
      - kubectl get pods -n $NAMESPACE -l app=claim-status-api
      - echo "Checking HPA status..."
      - kubectl get hpa claim-status-api-hpa -n $NAMESPACE || echo "HPA not yet active"
      - echo "Checking VPA status..."
      - kubectl get vpa claim-status-api-vpa -n $NAMESPACE || echo "VPA not installed or not yet active"
      - echo "Checking deployment events..."
      - kubectl describe deployment claim-status-api -n $NAMESPACE
      - echo "Checking pod details..."
      - kubectl get pods -n $NAMESPACE -l app=claim-status-api -o yaml | grep -A 20 "conditions:\|containerStatuses:" || true
      - echo "Waiting for rollout (timeout 5m)..."
      - kubectl rollout status deployment/claim-status-api -n $NAMESPACE --timeout=5m || (kubectl get events -n $NAMESPACE --sort-by='.lastTimestamp' | tail -20 && kubectl logs -n $NAMESPACE -l app=claim-status-api --tail=50 --all-containers=true || true && exit 1)
      - echo "Getting service details..."
      - kubectl get service claim-status-api -n $NAMESPACE
