version: 0.2

env:
  variables:
    DOTNET_ROOT: /root/.dotnet
    PATH: /root/.dotnet:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

phases:
  install:
    commands:
      - echo "Installing .NET 10 SDK..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 10.0 --quality daily --install-dir /root/.dotnet
      - ln -sf /root/.dotnet/dotnet /usr/local/bin/dotnet
      - dotnet --info | head -n 20
      - echo "Installing ReportGenerator for coverage merging..."
      - dotnet tool install --global dotnet-reportgenerator-globaltool
      - dotnet tool list --global
  pre_build:
    commands:
      - echo "Installing test dependencies..."
      - dotnet restore introspect2B.sln
      - echo "Running code analysis..."
      - dotnet build introspect2B.sln --configuration Release

  build:
    commands:
      - echo "Running unit tests with code coverage..."
      - dotnet test introspect2B.sln --configuration Release --filter "TestCategory!=Integration" --logger "console;verbosity=detailed" --logger "trx" --collect:"XPlat Code Coverage" --results-directory test-results -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile="**/*.generated.cs,**/Program.cs"
      - echo "Running integration tests..."
      - dotnet test introspect2B.sln --configuration Release --filter "TestCategory=Integration" --logger "console;verbosity=detailed" --logger "trx" --results-directory test-results || true

  post_build:
    commands:
      - echo "Test execution completed"
      - echo "Merging coverage reports..."
      - dotnet tool run reportgenerator -reports:"test-results/**/coverage.cobertura.xml" -targetdir:"test-results/merged-coverage" -reporttypes:"Cobertura"
      - echo "Test results location:"
      - find test-results -type f -name "*.trx" -o -name "*.xml" 2>/dev/null || echo "No test results found"

artifacts:
  files:
    - 'src/**/*'
  name: TestArtifact

reports:
  UnitTestReport:
    files:
      - 'test-results/**/*.trx'
    file-format: 'VSTEST'
  CodeCoverageReport:
    files:
      - 'test-results/merged-coverage/Cobertura.xml'
    file-format: 'COBERTURAXML'

cache:
  paths:
    - '/root/.dotnet/**/*'
    - '/root/.nuget/**/*'
