version: 0.2

env:
  variables:
    SERVICE_DIR: src/claim-status-api.Performance.Tests
    API_GATEWAY_STACK_NAME: claim-status-api-apigw
    ENVIRONMENT_NAME: dev
    AWS_PAGER: ""

phases:
  install:
    commands:
      - echo "Installing k6 and jq..."
      - curl -sL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -o k6.tgz
      - tar -xzf k6.tgz
      - mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/k6
      - rm -rf k6.tgz k6-v0.49.0-linux-amd64
      - apt-get update && apt-get install -y jq
  pre_build:
    commands:
      - echo "Detecting API Gateway endpoint and API key..."
      - |
        # Get API Gateway endpoint and API Key ID from CloudFormation stack outputs
        echo "Querying CloudFormation stack:" ${API_GATEWAY_STACK_NAME} "in region:" ${AWS_REGION}
        
        # First verify the stack exists
        if ! aws cloudformation describe-stacks \
          --stack-name "${API_GATEWAY_STACK_NAME}" \
          --region "${AWS_REGION}" \
          --no-cli-pager \
          --color off > /dev/null 2>&1; then
          echo "ERROR: CloudFormation stack '${API_GATEWAY_STACK_NAME}' not found in region ${AWS_REGION}"
          echo "Please ensure the API Gateway stack has been deployed first."
          exit 1
        fi
        
        # Retrieve stack outputs
        STACK_OUTPUTS=$(aws cloudformation describe-stacks \
          --stack-name "${API_GATEWAY_STACK_NAME}" \
          --region "${AWS_REGION}" \
          --query "Stacks[0].Outputs" \
          --output json \
          --no-cli-pager \
          --color off)
        
        echo "Stack outputs retrieved:"
        echo "$STACK_OUTPUTS" | jq .
        
        # Parse outputs
        export BASE_URL=$(echo "$STACK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="ApiEndpoint") | .OutputValue' | tr -d '\n')
        API_KEY_ID=$(echo "$STACK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="ApiKeyId") | .OutputValue' | tr -d '\n')
        
        echo "Parsed BASE_URL:" ${BASE_URL}
        echo "Parsed API_KEY_ID:" ${API_KEY_ID}
        
        # Validate we got the outputs before trying to fetch API key
        if [ -z "$BASE_URL" ] || [ "$BASE_URL" = "null" ]; then
          echo "ERROR: Could not retrieve API Gateway endpoint from stack outputs"
          echo "Expected output key 'ApiEndpoint' not found in stack"
          exit 1
        fi
        
        if [ -z "$API_KEY_ID" ] || [ "$API_KEY_ID" = "null" ]; then
          echo "ERROR: Could not retrieve API Key ID from stack outputs"
          echo "Expected output key 'ApiKeyId' not found in stack"
          exit 1
        fi
        
        # Retrieve the actual API key value
        echo "Fetching API key value for:" ${API_KEY_ID}
        export API_KEY=$(aws apigateway get-api-key \
          --api-key "${API_KEY_ID}" \
          --include-value \
          --region "${AWS_REGION}" \
          --query 'value' \
          --output text \
          --no-cli-pager \
          --color off 2>&1)
        
        # Check if API key retrieval was successful
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to retrieve API key value"
          echo "$API_KEY"
          exit 1
        fi
        
        echo "API Gateway Endpoint: ${BASE_URL}"
        echo "API Key ID: ${API_KEY_ID}"
        echo "API Key retrieved (${#API_KEY} characters)"
        
        # Final validation
        if [ -z "$API_KEY" ] || [ "$API_KEY" = "null" ] || [ "$API_KEY" = "None" ]; then
          echo "ERROR: Could not retrieve API key value"
          exit 1
        fi
  build:
    commands:
      - cd "$SERVICE_DIR"
      - k6 run performance-test.js --summary-export k6-summary.json
  post_build:
    commands:
      - echo "Performance test summary:"
      - cat k6-summary.json

artifacts:
  files:
    - "$SERVICE_DIR/k6-summary.json"
