AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Claim Status API workload to EKS using AWS::EKS::Manifest resources.

Parameters:
  EKSClusterName:
    Type: String
    Default: materclaims-cluster
    Description: Target EKS cluster name.
  Namespace:
    Type: String
    Default: materclaims
    Description: Kubernetes namespace for the workload.
  ImageTag:
    Type: String
    Default: latest
    Description: Container image tag to deploy from ECR.

Resources:
  ClaimStatusDeployment:
    Type: AWS::EKS::Manifest
    Properties:
      ClusterName: !Ref EKSClusterName
      Manifest:
        - !Sub |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: claim-status-api
              namespace: ${Namespace}
              labels:
                app: claim-status-api
                version: v1
            spec:
              replicas: 2
              strategy:
                type: RollingUpdate
                rollingUpdate:
                  maxSurge: 1
                  maxUnavailable: 0
              selector:
                matchLabels:
                  app: claim-status-api
              template:
                metadata:
                  labels:
                    app: claim-status-api
                    version: v1
                  annotations:
                    prometheus.io/scrape: "true"
                    prometheus.io/port: "8080"
                    prometheus.io/path: "/health"
                spec:
                  serviceAccountName: app-service-account
                  securityContext:
                    runAsNonRoot: true
                    runAsUser: 1000
                    fsGroup: 1000
                  containers:
                    - name: claim-status-api
                      image: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/claim-status-api:${ImageTag}
                      imagePullPolicy: Always
                      ports:
                        - containerPort: 8080
                          name: http
                          protocol: TCP
                      env:
                        - name: ASPNETCORE_ENVIRONMENT
                          value: "Production"
                        - name: AWS_DEFAULT_REGION
                          value: ${AWS::Region}
                        - name: AWS__DynamoDb__TableName
                          value: "claims"
                        - name: AWS__S3__BucketName
                          value: "claim-notes-${AWS::AccountId}"
                        - name: AWS__Bedrock__ModelId
                          value: "amazon.nova-2-lite-v1:0"
                        - name: AWS__Bedrock__InferenceProfileId
                          value: "us.amazon.nova-lite-v1:0"
                      resources:
                        requests:
                          memory: "256Mi"
                          cpu: "100m"
                        limits:
                          memory: "512Mi"
                          cpu: "500m"
                      livenessProbe:
                        httpGet:
                          path: /health
                          port: 8080
                        initialDelaySeconds: 30
                        periodSeconds: 10
                        timeoutSeconds: 5
                        failureThreshold: 3
                      readinessProbe:
                        httpGet:
                          path: /health
                          port: 8080
                        initialDelaySeconds: 10
                        periodSeconds: 5
                        timeoutSeconds: 3
                        failureThreshold: 3
                      securityContext:
                        allowPrivilegeEscalation: false
                        readOnlyRootFilesystem: true
                        runAsNonRoot: true
                        capabilities:
                          drop:
                            - ALL
                      volumeMounts:
                        - name: tmp
                          mountPath: /tmp
                        - name: cache
                          mountPath: /home/dotnet/.cache
                  volumes:
                    - name: tmp
                      emptyDir: {}
                    - name: cache
                      emptyDir: {}
                  affinity:
                    podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                            labelSelector:
                              matchExpressions:
                                - key: app
                                  operator: In
                                  values:
                                    - claim-status-api
                            topologyKey: kubernetes.io/hostname

  ClaimStatusService:
    Type: AWS::EKS::Manifest
    Properties:
      ClusterName: !Ref EKSClusterName
      Manifest:
        - !Sub |
            apiVersion: v1
            kind: Service
            metadata:
              name: claim-status-api
              namespace: ${Namespace}
              labels:
                app: claim-status-api
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
                service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
                service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                service.beta.kubernetes.io/aws-load-balancer-name: "claim-status-api"
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
            spec:
              type: LoadBalancer
              ports:
                - port: 80
                  targetPort: 8080
                  protocol: TCP
                  name: http
              selector:
                app: claim-status-api
