# yaml-language-server: $schema=https://json.schemastore.org/cloudformation.json
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  API Gateway for Claim Status API - RESTful endpoints for claim retrieval and summarization

Parameters:
  ServiceEndpoint:
    Type: String
    Description: Kubernetes LoadBalancer or NLB endpoint for claim-status-api
    Default: claim-status-api.example.com
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  DeploymentVersion:
    Type: String
    Default: v1
    Description: Bump this value to force a new API Gateway deployment

Resources:
  ClaimStatusApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub claim-status-api-${EnvironmentName}
      Description: GenAI-enabled Claim Status API with Bedrock summarization
      EndpointConfiguration:
        Types:
          - REGIONAL

  ClaimsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ParentId: !GetAtt ClaimStatusApi.RootResourceId
      PathPart: api

  ClaimsApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ParentId: !Ref ClaimsResource
      PathPart: claims

  ClaimIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ParentId: !Ref ClaimsApiResource
      PathPart: '{id}'

  SummarizeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ParentId: !Ref ClaimIdResource
      PathPart: summarize

  GetClaimMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ResourceId: !Ref ClaimIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub http://${ServiceEndpoint}/api/claims/{id}
        RequestParameters:
          integration.request.path.id: method.request.path.id
        RequestTemplates:
          application/json: '{"id": "$input.params(''id'')"}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
        - StatusCode: 404

  SummarizeClaimMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ClaimStatusApi
      ResourceId: !Ref SummarizeResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      RequestModels:
        application/json: !Ref SummarizeRequestModel
      Integration:
        Type: HTTP
        IntegrationHttpMethod: POST
        Uri: !Sub http://${ServiceEndpoint}/api/claims/{id}/summarize
        RequestParameters:
          integration.request.path.id: method.request.path.id
        RequestTemplates:
          application/json: |
            {
              "id": "$input.params('id')",
              "notesOverride": "$input.path('$.notesOverride')"
            }
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
        - StatusCode: 404
        - StatusCode: 500

  SummarizeRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ClaimStatusApi
      Name: SummarizeRequest
      ContentType: application/json
      Schema:
        type: object
        properties:
          notesOverride:
            type: string
            description: Optional override for claim notes

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetClaimMethod
      - SummarizeClaimMethod
    Properties:
      RestApiId: !Ref ClaimStatusApi
      Description: !Sub "Deployment-${EnvironmentName}-${DeploymentVersion}"
      StageName: !Ref EnvironmentName

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub claim-status-api-${EnvironmentName}-key
      Enabled: true
      GenerateDistinctId: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub claim-status-api-${EnvironmentName}-plan
      ApiStages:
        - ApiId: !Ref ClaimStatusApi
          Stage: !Ref EnvironmentName
      Throttle:
        RateLimit: 100.0
        BurstLimit: 50
      Quota:
        Limit: 100000
        Period: MONTH

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub |
      https://${ClaimStatusApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}
    Export:
      Name: !Sub ClaimStatusApiEndpoint-${EnvironmentName}

  ApiId:
    Description: API Gateway ID
    Value: !Ref ClaimStatusApi
    Export:
      Name: !Sub ClaimStatusApiId-${EnvironmentName}

  ApiKeyId:
    Description: API Key ID
    Value: !Ref ApiKey
    Export:
      Name: !Sub ClaimStatusApiKeyId-${EnvironmentName}

  UsagePlanId:
    Description: Usage Plan ID
    Value: !Ref UsagePlan
    Export:
      Name: !Sub ClaimStatusApiUsagePlanId-${EnvironmentName}