# Dapr Pub/Sub Component using AWS SNS/SQS
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagepubsub
  namespace: dapr-demo
spec:
  type: pubsub.aws.snssqs
  version: v1
  metadata:
  - name: region
    value: "us-east-1"
  - name: accessKey
    value: ""
  - name: secretKey
    value: ""
  - name: sessionToken
    value: ""
  - name: disableEntityManagement
    value: "true"
  - name: assetsManagementTimeoutSeconds
    value: "5"
scopes:
- product
- order