source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins
gem 'webrick', '~> 1.8'
gem 'jekyll-seo-tag'
gem 'jekyll-relative-links'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-titles-from-headings'
